### ISSUE TITLE
Chapter7 Error: FileNotFoundError: [Errno 2] No such file or directory: '/kaniko/.docker/config.json'

### ISSUE THREAD

**Issue by Lighty55** [PacktPublishing/Machine-Learning-on-Kubernetes#12]
Platform: minikube version: v1.24.0

I'm doing the chapter 07 guide with the build push image though airflow and got this error
FileNotFoundError: [Errno 2] No such file or directory: '/kaniko/.docker/config.json'

![image](https://user-images.githubusercontent.com/82205076/237020395-ff2ff875-bd06-4dde-a481-81983a94486e.png)

![image](https://user-images.githubusercontent.com/82205076/237020573-1541f033-76db-46c0-8251-5448dcebb9da.png)

Have anyone faced this error before?      
Is there a solution for this?

**Comment by webmakaka** [comment]
Hi, @Lighty55!
Did you pass step https://github.com/PacktPublishing/Machine-Learning-on-Kubernetes/issues/10

If yes, can you share working manifests?

===========

I think everything worked for me a year ago. Or i solved all errors by myself. 
https://github.com/webmakaka/Machine-Learning-on-Kubernetes/blob/master/docs/07-model-deployment-and-automation.md

**Comment by Lighty55** [comment]
> Hi, @Lighty55! Did you pass step #10
> 
> If yes, can you share working manifests?
> 
> ===========
> 
> I think everything worked for me a year ago. Or i solved all errors by myself. https://github.com/webmakaka/Machine-Learning-on-Kubernetes/blob/master/docs/07-model-deployment-and-automation.md

I didn't face this error, but got the one in #6 but managed to fix it by changing the git repo and the executor in airflow.cfg from CeleryExecutor to SequentialExecutor before executing

And I'm using this version of the OLM and minikube v1.24.0
- kubectl create -f https://github.com/operator-framework/operator-lifecycle-manager/releases/download/v0.21.1/crds.yaml
- kubectl create -f https://github.com/operator-framework/operator-lifecycle-manager/releases/download/v0.21.1/olm.yaml
