### ISSUE TITLE
value: .<IP Address>.nip.io in file /manifests/kfdef/ml-platform.yam is correct?

### ISSUE THREAD

**Issue by webmakaka** [PacktPublishing/Machine-Learning-on-Kubernetes#7]
Hello!

Is there name before IP missing or everything is OK?

https://github.com/PacktPublishing/Machine-Learning-on-Kubernetes/blob/adef406c1a40182f9c2812774e651a6c4ef168c9/manifests/kfdef/ml-platform.yaml#L89

Thanks

**Comment by mastash3ff** [comment]
No. This is intenional.

**Comment by webmakaka** [comment]
yes, this is correct.
